# Generated by Django 3.2.2 on 2024-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_event_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
