# Generated by Django 3.2.2 on 2024-03-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_event_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scanned_events',
            field=models.ManyToManyField(blank=True, to='project.Event'),
        ),
    ]
